-- Create sources table
create table if not exists sources (
  id bigint generated by default as identity primary key,
  subreddit text,
  url text,
  created_at timestamptz default now()
);

-- Create ideas table with foreign key to sources
create table if not exists ideas (
  id bigint generated by default as identity primary key,
  title text not null,
  elevator_pitch text,
  pain_point text,
  topic text,
  score int,
  source_id bigint references sources(id) on delete set null,
  created_at timestamptz default now()
);

-- Create subscriptions table (for future use in T6)
create table if not exists subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid,
  email text,
  topics text[],
  is_active boolean default true,
  unsubscribe_token text unique,
  created_at timestamptz default now()
);

-- Create indexes for performance
create index if not exists idx_ideas_topic on ideas(topic);
create index if not exists idx_ideas_score on ideas(score);
create index if not exists idx_ideas_created_at on ideas(created_at);
create index if not exists idx_ideas_source_id on ideas(source_id);
create index if not exists idx_sources_subreddit_url on sources(subreddit, url);

-- Create unique constraint on sources to prevent duplicates
-- Using a unique expression index to handle NULL urls properly
create unique index if not exists idx_sources_unique_subreddit_url 
  on sources(subreddit, coalesce(url, ''));

-- Enable Row Level Security
alter table sources enable row level security;
alter table ideas enable row level security;
alter table subscriptions enable row level security;

-- Create RLS policies for public read access to ideas and sources
create policy "Allow public read access to ideas"
  on ideas for select
  using (true);

create policy "Allow public read access to sources"
  on sources for select
  using (true);

-- Create RLS policies for public insert access (for API endpoints)
create policy "Allow public insert to ideas"
  on ideas for insert
  with check (true);

create policy "Allow public insert to sources"
  on sources for insert
  with check (true);

-- Subscriptions table policies (restrictive for now, will be updated in T6)
create policy "Allow public read access to subscriptions"
  on subscriptions for select
  using (true);

